version: "3.8"

services:

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped


  backend:
    image: sandusewwandi/devops_backend:latest
    container_name: backend

    ports:
      - "5000:5000"

    environment:
      JWT_SECRET: dummysecret
      MONGODB_URI: mongodb://mongo:27017/devops
      NODE_ENV: production

      CLOUDINARY_CLOUD_NAME: djzjdus1k
      CLOUDINARY_API_KEY: 823756362343243
      CLOUDINARY_API_SECRET: FwkT9WUwifSXJn-Mev1-2gpvw5c

      ADMIN_EMAIL: admin@plant.com
      ADMIN_PASS: Admin123

      CORS_ORIGIN: http://localhost:5173,http://${PUBLIC_IP}:5173
      MAX_FILE_SIZE: 10485760
      UPLOAD_PATH: /tmp/uploads

    volumes:
      - uploads_data:/tmp/uploads
      - ./logs:/app/logs

    depends_on:
      - mongo

    restart: unless-stopped


  frontend:
    image: sandusewwandi/devops_frontend:latest
    container_name: frontend

    ports:
      - "5173:5173"

    environment:
      VITE_API_URL: http://${PUBLIC_IP}:5000

    depends_on:
      - backend

    restart: unless-stopped


volumes:
  mongo_data:
  uploads_data:
